# Generated by Django 3.2 on 2022-12-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmationcodes',
            name='confirmation_code',
        ),
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=150, verbose_name='Код подтверждения'),
        ),
    ]
