# Generated by Django 3.2 on 2022-12-13 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20221213_2150'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfirmationCodes',
        ),
    ]
