# Generated by Django 3.2 on 2022-12-17 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20221217_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='categorie',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='title',
            old_name='genre',
            new_name='genres',
        ),
    ]
