# Generated by Django 3.2 on 2022-12-20 18:10

from django.db import migrations, models

import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_review_unique_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.CharField(max_length=50, unique=True, validators=[reviews.validators.slug_validator]),
        ),
        migrations.AlterField(
            model_name='genres',
            name='slug',
            field=models.CharField(max_length=50, unique=True, validators=[reviews.validators.slug_validator]),
        ),
    ]
